### ISSUE TITLE
Error when running lines program (Attribute error)

### ISSUE THREAD

**Issue by Charlaiz** [stefsmeets/lines#3]
Hello, I've just downloaded and installed the software and necessary packages. No problems in that regard, but when i try to run the script I get the following error:

"Loading data: C:\Users\karel\Box\FAU-crown\data\KA001_000_80_0001p.xye
       shape: (4826L, 3L)
       R_exp: 0.119%
Interpolation mode for background correction

The highest and lowest values are added by default for convenience. In the case that they are removed, only the values in the background range will be printed.

Loading data: bg (--correct)
       shape: (2L, 2L)
       R_exp: 1.750%
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\karel\Anaconda3\envs\py27\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Users\karel\Anaconda3\envs\py27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\karel\Anaconda3\envs\py27\lib\site-packages\lines-1.3.0-py2.7.egg\lines\lines.py", line 2307, in run_script
    out=options.bg_output, topas_bg=options.topas_bg, xrs=options.xrs_out)
**AttributeError: 'Namespace' object has no attribute 'xrs_out'**

I'm not very familiar with python or programming in general. Any idea what causes this error and how to solve?"

Thank you,
Karel

**Comment by stefsmeets** [comment]
Thank you for your message. I also noticed this a few days ago. I had already fixed it, but didn't upload the code yet (12cceeb03f7405835a3ce7a57c1e1f371f3fa535). Can you try to reinstall to see if it works now?

**Comment by Charlaiz** [comment]
Excellent, everything seems to work fine now. Thank a lot!

**Comment by stefsmeets** [comment]
Great! Happy to hear!
